export { default } from './ResidentialSolar'
export { default as ResidentialSolar } from './ResidentialSolar'
export { default as ResidentialHero } from './ResidentialHero'
export { default as ResidentialOverview } from './ResidentialOverview'
export { default as ResidentialSystemSizes } from './ResidentialSystemSizes'
export { default as ResidentialBenefits } from './ResidentialBenefits'
export { default as ResidentialProcess } from './ResidentialProcess'
export { default as ResidentialContact } from './ResidentialContact'
export { default as ResidentialFaq } from './ResidentialFaq'
