import { useState } from 'react'

const officialFaqs = [
  {
    q: '1. What is Residential Solar Installation in Patna?',
    a: 'Residential Solar Installation in Patna involves designing and installing a rooftop solar system for a home to generate clean electricity and reduce dependence on grid power.',
  },
  {
    q: '2. Is solar suitable for homes in Patna?',
    a: 'Yes, Patna receives substantial sunlight, making rooftop solar a practical option for many residential properties.',
  },
  {
    q: '3. How much can I save with residential solar?',
    a: 'Savings depend on your system capacity, electricity consumption, tariff, sunlight, and net-metering arrangements.',
  },
  {
    q: '4. What size solar system does my home need?',
    a: 'The ideal size for a Residential Solar Installation in Patna depends primarily on your monthly electricity consumption and available rooftop area.',
  },
  {
    q: '5. Can I install solar on a small rooftop?',
    a: 'Yes, a properly planned system can be designed according to the available rooftop space and your energy requirements.',
  },
  {
    q: '6. Does residential solar work during cloudy weather?',
    a: 'Solar panels continue generating electricity in cloudy conditions, although their output is generally lower than on sunny days.',
  },
  {
    q: '7. What is net metering in a residential solar system?',
    a: 'Net metering allows eligible surplus electricity generated by your solar system to be exported to the grid according to applicable utility regulations.',
  },
  {
    q: '8. How long do residential solar panels last?',
    a: 'Quality solar panels are designed for long-term operation, with many manufacturers offering warranties extending to around 25 years.',
  },
  {
    q: '9. What equipment is required for Residential Solar Installation in Patna?',
    a: 'A typical system includes solar panels, an inverter, mounting structures, electrical protection equipment, wiring, and applicable metering components.',
  },
  {
    q: '10. Is rooftop solar a good investment for homeowners?',
    a: 'Yes, a correctly sized Residential Solar Installation in Patna can help reduce electricity expenses while providing clean energy for years.',
  },
  {
    q: '11. Can solar be installed on a modern villa?',
    a: 'Absolutely; residential solar systems can be designed to complement the rooftop layout and aesthetics of villas and contemporary homes.',
  },
  {
    q: '12. How do I get started with Residential Solar Installation in Patna?',
    a: 'Start with a professional rooftop and electricity-consumption assessment to determine the appropriate system size and installation requirements.',
  },
]

export default function ResidentialFaq() {
  const [openIndex, setOpenIndex] = useState(0)

  return (
    <section className="py-24 bg-[#F8FAF9] border-t border-emerald-100/80 overflow-hidden">
      <div className="site-container max-w-4xl">
        <div className="text-center mb-16">
          <span className="text-xs font-extrabold uppercase tracking-widest text-emerald-700 block mb-2">
            GOT QUESTIONS?
          </span>
          <h2 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
            Frequently Asked Questions
          </h2>
          <p className="mt-3 text-sm text-slate-600 max-w-xl mx-auto">
            Everything you need to know about Residential Solar Installation in Patna, net metering, savings, and performance.
          </p>
        </div>

        <div className="space-y-3.5">
          {officialFaqs.map((faq, index) => {
            const isOpen = openIndex === index
            return (
              <div
                key={index}
                className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white transition-all shadow-xs"
              >
                <button
                  type="button"
                  onClick={() => setOpenIndex(isOpen ? null : index)}
                  className="flex w-full items-center justify-between p-5 text-left transition hover:bg-slate-50/60 cursor-pointer"
                  aria-expanded={isOpen}
                >
                  <span className="text-sm sm:text-base font-bold text-slate-900 pr-4">
                    {faq.q}
                  </span>
                  <span
                    className={`flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-emerald-100/70 text-emerald-700 transition-transform duration-200 ${
                      isOpen ? 'rotate-180 bg-[#064E3B] text-white' : ''
                    }`}
                  >
                    <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                    </svg>
                  </span>
                </button>

                {isOpen && (
                  <div className="px-5 pb-5 pt-0">
                    <div className="border-t border-slate-100 pt-3.5 text-xs sm:text-sm leading-relaxed text-slate-600">
                      {faq.a}
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
