export { default } from './IndustrialSolar'
export { default as IndustrialSolar } from './IndustrialSolar'
export { default as IndustrialHero } from './IndustrialHero'
export { default as IndustrialFeatureCards } from './IndustrialFeatureCards'
export { default as IndustrialOverview } from './IndustrialOverview'
export { default as IndustrialResults } from './IndustrialResults'
export { default as IndustrialBenefits } from './IndustrialBenefits'
export { default as IndustrialSystemSizes } from './IndustrialSystemSizes'
export { default as IndustrialProcess } from './IndustrialProcess'
export { default as IndustrialContact } from './IndustrialContact'
export { default as IndustrialFaq } from './IndustrialFaq'
